# Default values for prom2teams.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: idealista/prom2teams
  tag:
  pullPolicy: IfNotPresent

resources:
 requests:
   cpu: 100m
   memory: 128Mi
 limits:
   cpu: 200m
   memory: 200Mi

service:
  type: ClusterIP
  port: 8089
  monitoring_port: 9090

prom2teams:
  # environment:
    # devops: https://prosoftke.webhook.office.com/webhookb2/49944610-ed87-452c-8a1b-b69efe24426e@e0ba1e1a-2c8d-4a6d-aad6-5319da3aa328/IncomingWebhook/70d92eb4959d428797502817ecd42e44/0dfb97d4-83a6-413a-85af-064d8f6b5343
  host: 0.0.0.0
  port: 8089
  monitoring_port: 9090
  connector: 
    devops: https://prosoftke.webhook.office.com/webhookb2/49944610-ed87-452c-8a1b-b69efe24426e@e0ba1e1a-2c8d-4a6d-aad6-5319da3aa328/IncomingWebhook/70d92eb4959d428797502817ecd42e44/0dfb97d4-83a6-413a-85af-064d8f6b5343
  connectors:
    devops: https://prosoftke.webhook.office.com/webhookb2/49944610-ed87-452c-8a1b-b69efe24426e@e0ba1e1a-2c8d-4a6d-aad6-5319da3aa328/IncomingWebhook/ee4b05f6ca4c42538d7b1602d1c0b9d3/0dfb97d4-83a6-413a-85af-064d8f6b5343
  # - bordel: https://prosoftke.webhook.office.com/webhookb2/49944610-ed87-452c-8a1b-b69efe24426e@e0ba1e1a-2c8d-4a6d-aad6-5319da3aa328/IncomingWebhook/70d92eb4959d428797502817ecd42e44/0dfb97d4-83a6-413a-85af-064d8f6b5xxx

  # group_alerts_by can be one of
  # ("name" | "description" | "instance" | "severity" | "status" | "summary" | "fingerprint" | "runbook_url")
  group_alerts_by:
  # loglevel can be one of (DEBUG | INFO | WARNING | ERROR | CRITICAL)
  loglevel: INFO
  templatepath: /opt/prom2teams/helmconfig/teams.j2
  config: /opt/prom2teams/helmconfig/config.ini
  extraEnv: {}

# Security Context properties
securityContext:
  # enabled is a flag to enable Security Context
  enabled: true
  # runAsUser is the user ID used to run the container
  runAsUser: 101
  # runAsGroup is the primary group ID used to run all processes within any container of the pod
  runAsGroup: 101
  # fsGroup is the group ID associated with the container
  fsGroup: 101
  # readOnlyRootFilesystem is a flag to enable readOnlyRootFilesystem for the Hazelcast security context
  readOnlyRootFilesystem: true
